### ISSUE TITLE
Can you build binaries for Linux OSes?

### ISSUE THREAD

**Issue by Lirk88** [oleksis/youtube-dl-gui#97]
- [ x ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x ] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [ x ] **I assure** that i am using the latest version of **youtube-dl**
  - [ x ] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ x ] Feature request (request for a new functionality)
- [ x ] Question
- [ ] Other

### Question

Can you build binaries for Linux OSes? M.B. Snap/AppImage/Archived Package/DEB/RPM? Binary from this repository doesn't work on Ubuntu 22.04 with installed required python modules.

**Comment by oleksis** [comment]
Check the Releases section the [yt-dlg asset](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg) or the Downloads section in the [yt-dlg](https://yt-dlg.github.io/yt-dlg/#downloads) site

**Comment by DraconicNEO** [comment]
> Check the Releases section the [yt-dlg asset](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.3/yt-dlg) or the Downloads section in the [yt-dlg](https://yt-dlg.github.io/yt-dlg/#downloads) site

Do you think you will be possible to support [flatpak](https://flatpak.org). I think it will be better and easier if this app had a flatpak version since it could work on any distro. And unlike raw binaries they don't break as easily from Linux updates.

**Comment by Gr3q** [comment]
I don't have time to test and create 

Relevant flatpak docs:
* https://docs.flatpak.org/en/latest/first-build.html
* https://docs.flatpak.org/en/latest/python.html

You probably need to build the requirements:
`python3 flatpak-pip-generator --requirements-file=requirements.txt`, it will output extra modules to `python3-yt-dlg.json`. I know you don't have a `requirements.txt` but I'm sure `flatpak-pip-generator` has something alternative.

Flatpak manifest that might work excluding the extra work that the dependencies might need (like wxpython...).
```
app-id: org.flatpak.yt-dlg
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: yt-dlg
modules:
   - python3-yt-dlg.json
   name: yt-dlg
   buildsystem: simple
   build-commands:
     - pip3 install --prefix=/app --no-deps .
   sources:
     - type: archive
       url: https://github.com/oleksis/youtube-dl-gui/archive/refs/tags/v1.8.5.tar.gz
       sha256: 8b1f9815857228a002680e2f64fc421055098c6dcfed6f6be17274b0cf45ca4a
```
